### ISSUE TITLE
☂️ Make internals a part of tarantool.io

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/tarantool-internals#3]
Make internals a part of tarantool.io, just like other projects.

www.tarantool.io/en/dev/core?

# Building docs

- [x] Build with tarantool/doc-builder:
  - tarantool/doc-builder#18,
  - tarantool/tarantool-internals#4
- [x] #6

# Deployment & CI/CD

- [x] #5
- [x] #7
- [x] #8
- [ ] Add a link to test deployment to PRs

# Backend

- [x] https://github.com/tarantool/tarantool.io/issues/1206
- [x] #16
- [ ] Link to internals in the menu (?)

# doc.tarantool.dev

- [ ] #15

# Docs quality

- [x] #17
- [ ] #21

**Comment by rosik** [comment]
Probably, the destination is https://www.tarantool.io/en/doc/2.3/dev_guide/internals/
